name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Release with Gradle
      run: ./gradlew assembleRelease
    - name: Setup git
      run: |
        git config --global user.name ${{ secrets.ACTIONS_USERNAME }}
        git config --global user.email ${{ secrets.ACTIONS_EMAIL }}
    - name: Add, Commit and Push APK
      run: |
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git pull github ${GITHUB_REF} --ff-only

        git add app/release/*

        git commit -m "Update release apk"
        git push github HEAD:${GITHUB_REF}

