name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew assemble
    - name: Copy unsigned release file to release folder
      run:  |
        APP=$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f2)
        mkdir -p app/release
        cp "app/build/outputs/apk/release/app-release-unsigned.apk" "app/release/$APP.apk"
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/release
        signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
        keyPassword: ${{ secrets.KEYPASSWORD }}
    - name: Setup git
      run: |
        git config --local user.name ${{ secrets.ACTIONS_USERNAME }}
        git config --local user.email ${{ secrets.ACTIONS_EMAIL }}
    - name: Rename, Add, Commit and Push APK
      run: |
        APP=$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f2)
        mv -f "app/release/$APP-signed.apk" "app/release/$APP.apk" 
        
        git pull.ff only
        
        git add "app/release/$APP.apk"
        git commit -m "Update release apk"

        git push
