name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew assemble
    - name: Copy unsigned release file to release folder
      run:  |
        mkdir -p app/release/temp
        cp app/build/outputs/apk/release/app-release-unsigned.apk app/release/temp/temp.apk
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/release/temp
        signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
        keyPassword: ${{ secrets.KEYPASSWORD }}
    - name: Rename signed file
      run:  mv app/release/temp/temp-signed.apk app/release/Lock.apk
    - name: Remove temp signing folder
      run:  rm -r app/release/temp
    - name: Setup git
      run: |
        git config --local user.name ${{ secrets.ACTIONS_USERNAME }}
        git config --local user.email ${{ secrets.ACTIONS_EMAIL }}
    - name: Add, Commit and Push APK
      run: |
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git pull github ${GITHUB_REF} --ff-only

        git add app/release/Lock.apk

        git commit -m "Update release apk"
        git push github HEAD:${GITHUB_REF}
